### ISSUE TITLE
Recursive loading of a folder

### ISSUE THREAD

**Issue by 5an1ty** [jacoborus/wiretree#16]
A nice to have would be to be able to load a folder structure like this:
Aoo -> Plugins -> Plugin1 -> index.js
App -> Plugins -> Plugin2 -> index.js

where you could just execute
tree.folder('./Plugins');

and load all the plugins in the plugins folder.

**Comment by jacoborus** [comment]
Hi Ruben, this behaviour is intentionally because plugins can load other js files, and I think the right place for this js files is a subfolfer. You can chain folder loads:

```js
tree
.folder('folder1')
.folder('folder2')
```

**Comment by jacoborus** [comment]
Do you think a 'subfolder' method could be useful?

**Comment by 5an1ty** [comment]
As you said I can just chain .folder calls so there is no real need besides making the tree a little bit more compact.
