### ISSUE TITLE
Singletons

### ISSUE THREAD

**Issue by 5an1ty** [jacoborus/wiretree#17]
When using wtDone it looks like the wiretree constructor get's called every time it is depended upon. Can this behavior be modified to only be called on the .resolve() method?

**Comment by jacoborus** [comment]
Wiretree is already calling plugins constructor once. It creates plugins at the time inserts them in tree, time before resolve their values. All resolved plugins are cached, so yo don't have to worry about calling constructor several times, it is not happening. At least I do not detect this behavior.

(english it's not my first language) Am I misunderstanding your question?

**Comment by 5an1ty** [comment]
When using wtDone I experience multiple calls to the constructor and I don't think that behavior is intentional:

exports.wiretree = function(wtDone) {
    console.log('hello');
    doSomeAsyncOp(wtDone);
}

Every time you require this plugin console.log('hello'); will be called not only when using tree.resolve();

**Comment by jacoborus** [comment]
I can't test it right now, but if you are right that's a bug. A really big one

**Comment by jacoborus** [comment]
Hi @5an1ty , thanks for pointing that. Let me know if you find another bug or need help with wiretree please.

**Comment by 5an1ty** [comment]
Thanks @jacoborus! Wiretree is proving tot be extremely useful for the application i'm writing.
